In [15]:
import pandas as pd
import numpy as np

In [37]:
# 04/20/2022 and 04/22/2022 qqq puts/calls open interest
qqq_4_20_2022_and_4_22_2022 = pd.read_csv(r'qqq_4_20_2022_and_4_22_2022.csv')

In [38]:
qqq_4_20_2022_and_4_22_2022

,Stock quote and option quote for QQQ on 4/19/22 23:34:42,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
0,UNDERLYING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LAST,LX,Net Chng,BID,BX,ASK,AX,Size,Volume,Open,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,346.26,Q,7.57,343.31,NaN,343.8,NaN,"37 x 3,369",56515684,338.03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,UNDERLYING EXTRA INFO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Last Size,Yield,PE,Div,Div.Freq,Ex Div.Date,52High,52Low,Shares,Beta,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,17 MAR 23 (331) 100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,31 MAR 23 (345) 100 (Quarterlys),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,16 JUN 23 (422) 100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,15 DEC 23 (604) 100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,19 JAN 24 (639) 100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
drop_list = [x for x in range(6)]
print(drop_list)

[0, 1, 2, 3, 4, 5]

In [40]:
df = qqq_4_20_2022_and_4_22_2022.drop(axis=0, index =drop_list)
# df = qqq_4_20_2022_and_4_22_2022

In [41]:
df.head(20)

,Stock quote and option quote for QQQ on 4/19/22 23:34:42,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
6,20 APR 22 (0) 100 (Weeklys),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,LAST,LX,Net Chng,%Change,AS,BS,Open,Volume,...,%Change,AS,BS,Open,Volume,Open.Int,Delta,Impl Vol,Low,High
8,NaN,NaN,27.33,C,0,0.00%,12,14,0,0,...,-33.33%,3,0,0.04,63,87,0,78.46%,0.01,0.04
9,NaN,NaN,27.76,N,2.37,9.33%,14,9,27.76,10,...,-75.00%,3,0,0.03,592,1315,0,75.94%,0.01,0.04
10,NaN,NaN,26.21,I,0,0.00%,14,14,0,0,...,-80.00%,3,246,0.05,104,783,0,81.81%,0.01,0.05
11,NaN,NaN,27.86,M,8.18,41.57%,14,12,27.86,1,...,-83.33%,10,187,0.04,2887,306,0,79.06%,0.01,0.04
12,NaN,NaN,26.85,M,4.63,20.84%,14,14,26.48,5,...,-71.43%,3,203,0.05,477,503,0,76.32%,0.01,0.06
13,NaN,NaN,27.6,Z,6.52,30.93%,14,14,25.6,2,...,-85.71%,3,221,0.06,413,522,0,73.58%,0.01,0.08
14,NaN,NaN,24.73,C,6.9,38.70%,14,14,18.24,10,...,-71.43%,2,241,0.08,1111,1634,0,70.84%,0.01,0.1
15,NaN,NaN,24.56,X,4.06,19.80%,14,14,24.56,1,...,-77.78%,102,361,0.12,1657,112,-0.01,70.29%,0.01,0.13
16,NaN,NaN,22.48,J,2.45,12.23%,14,14,15.9,24,...,-90.00%,150,280,0.13,573,487,-0.01,70.84%,0.01,0.15
17,NaN,NaN,22.4,C,8.07,56.32%,14,14,17.45,6,...,-75.00%,101,313,0.15,1025,433,-0.01,67.89%,0.01,0.19
18,NaN,NaN,16.61,C,2.14,14.79%,14,9,13.8,7,...,-71.43%,95,160,0.19,896,1022,-0.01,66.25%,0.01,0.23
19,NaN,NaN,20.3,N,5.12,33.73%,14,14,13.43,1015,...,-68.75%,104,202,0.21,3632,4647,-0.01,64.39%,0.02,0.3
20,NaN,NaN,14.91,C,2.58,20.92%,14,14,14.91,2,...,-80.95%,142,111,0.3,1309,864,-0.02,63.22%,0.02,0.37
21,NaN,NaN,19.13,P,8.54,80.64%,14,14,13.97,4,...,-80.00%,86,163,0.36,2530,766,-0.02,60.94%,0.02,1.97
22,NaN,NaN,16.67,I,6.27,60.29%,14,14,10.38,12,...,-76.67%,82,310,0.39,5628,969,-0.02,58.53%,0.03,0.6
23,NaN,NaN,17.15,J,8.44,96.90%,14,14,9.92,22,...,-81.08%,118,64,0.51,2517,1702,-0.03,57.93%,0.02,0.75
24,NaN,NaN,13.44,M,2.99,28.61%,14,14,8.8,449,...,-79.59%,74,182,0.63,14262,9717,-0.03,55.68%,0.04,2.07
25,NaN,NaN,12.86,M,3.15,32.44%,12,12,8.52,78,...,-81.36%,91,72,0.8,2957,1645,-0.04,55.10%,0.05,1.11

In [47]:
import re
matches = ("7/17/7777 77:77", 'jwdajwf','3/17/7777 77:77')
r = re.compile('.*/.*/.*:.*')
if r.match('x/x/xxxx xx:xx') is not None:
#    print(matches)
    print(f'{r.match}')

<built-in method match of re.Pattern object at 0x00000242C7B9DC60>

In [12]:
pattern = re.compile("o")
print(pattern.match("dog"))      # No match as "o" is not at the start of "dog".
print(pattern.match("dog", 1))
if pattern.match("dog",1) is not None:
    print('hello')

None
<re.Match object; span=(1, 2), match='o'>
hello

In [13]:
pattern = re.compile("dog")
if pattern.match("dog") is not None:
    print('hello')

hello

In [ ]:
import re

In [ ]:
pattern = re.compile("o")

In [48]:
#identify start of options chain per expiry
for i in df['Stock quote and option quote for QQQ on 4/19/22 23:34:42']:
    if i is not np.nan:
        print(i)

20 APR 22  (0)  100 (Weeklys)
22 APR 22  (2)  100 (Weeklys)
25 APR 22  (5)  100 (Weeklys)
27 APR 22  (7)  100 (Weeklys)
29 APR 22  (9)  100 (Weeklys)
2 MAY 22  (12)  100 (Weeklys)
4 MAY 22  (14)  100 (Weeklys)
6 MAY 22  (16)  100 (Weeklys)
9 MAY 22  (19)  100 (Weeklys)
11 MAY 22  (21)  100 (Weeklys)
13 MAY 22  (23)  100 (Weeklys)
16 MAY 22  (26)  100 (Weeklys)
18 MAY 22  (28)  100 (Weeklys)
20 MAY 22  (30)  100
23 MAY 22  (33)  100 (Weeklys)
25 MAY 22  (35)  100
27 MAY 22  (37)  100 (Weeklys)
17 JUN 22  (58)  100
30 JUN 22  (71)  100 (Quarterlys)
15 JUL 22  (86)  100
19 AUG 22  (121)  100
16 SEP 22  (149)  100
30 SEP 22  (163)  100 (Quarterlys)
16 DEC 22  (240)  100
30 DEC 22  (254)  100 (Quarterlys)
20 JAN 23  (275)  100
17 MAR 23  (331)  100
31 MAR 23  (345)  100 (Quarterlys)
16 JUN 23  (422)  100
15 DEC 23  (604)  100
19 JAN 24  (639)  100